[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://visvabharati.irins.org/.*"]

[build]
  command = "bun run build"
  publish = "dist"

[[redirects]]
  from = "/*.html"
  to = "/:splat.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  framework = "vite"
